### ISSUE TITLE
Artifact with this name already exists

### ISSUE THREAD

**Issue by mtamiola-priv** [zaproxy/action-api-scan#45]
Since moving to v0.9 (and upload-artifactv4) I have problem with following error
`Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
`
Seems there was some breaking changes here https://github.com/actions/upload-artifact/issues/480

This is how I run action
```
      - name: zap-api-scan
        uses: zaproxy/action-api-scan@77dfa9a647bb0f583e39d4df8531634d6ddd8df4 # 0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: ./api-oas.json
          cmd_options: '-a'
          fail_action: false
          allow_issue_writing: false
```
tried to add 
`artifact_name: zap-report-${{ github.run_id }}-${{ github.run_attempt }}`
but did not help. Any idea how to fix that?
